# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pygame',
        'pygame.font',
        'pygame.display',
        'pygame.event',
        'pygame.draw',
        'pygame.image',
        'pygame.mixer',
        'pygame.time',
        'pygame.key',
        'pygame.mouse',
        'sys',
        'json',
        'collections',
        'random',
        'math',
        'copy',
        'utils',
        'unites',
        'sauvegarde',
        'competences',
        'unit_selector',
        'placement',
        'hexarene',
        'menu',
        'jeu',
        'input_mod',
        'affichage',
        'animations',
        'boutique',
        'inventaire',
        'tour',
        'tuto',
        'ia',
        'ia_selector',
        'layout',
        'campagne'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='HexMaster',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
